import { generateText, jsonSchema, LanguageModel } from "ai";

export interface StepRecord {
  timestamp: string;
  toolName: string;
  args: Record<string, any>;
  stdoutSummary?: string;
  tokenCountEstimate: number;
}

export interface ToolSpec {
  name: string;
  description: string;
  parameters: Record<string, any>;
}

export interface AgenticDecision {
  type: "tool_call" | "complete" | "fail";
  toolCall?: {
    id: string;
    name: string;
    args: Record<string, any>;
  };
  message?: string;
}

export interface LLMOrchestrator {
  generateNextTurn(
    sessionId: string,
    currentHistory: StepRecord[],
    availableTools: ToolSpec[],
  ): Promise<AgenticDecision>;
}

export interface LLMOrchestratorOptions {
  model: LanguageModel;
  systemInstruction?: string;
}

export class VercelLLMOrchestrator implements LLMOrchestrator {
  private model: LanguageModel;
  private systemInstruction: string;

  constructor(options: LLMOrchestratorOptions) {
    this.model = options.model;
    this.systemInstruction =
      options.systemInstruction || "You are a helpful assistant.";
  }

  /**
   * Transforms internal step history into the unified Vercel AI SDK chat schema,
   * configures tool mappings, and returns the next agentic decision.
   */
  async generateNextTurn(
    sessionId: string,
    currentHistory: StepRecord[],
    availableTools: ToolSpec[],
  ): Promise<AgenticDecision> {
    try {
      // 1. Map currentHistory to Vercel AI SDK CoreMessages (retains args/result inside message parts)
      const messages: any[] = [];
      for (let i = 0; i < currentHistory.length; i++) {
        const step = currentHistory[i];
        const toolCallId = `call_${sessionId}_${i}`;

        // Map assistant decision to run the tool (args is correct here for ToolCallPart)
        messages.push({
          role: "assistant",
          content: [
            {
              type: "tool-call",
              toolCallId,
              toolName: step.toolName,
              args: step.args,
            },
          ],
        });

        // Map matching execution output of the tool (result is correct here for ToolResultPart)
        messages.push({
          role: "tool",
          content: [
            {
              type: "tool-result",
              toolCallId,
              toolName: step.toolName,
              result: step.stdoutSummary ?? "",
            },
          ],
        });
      }

      // 2. Translate internal ToolSpec formats into the SDK's expected tool structure
      const tools: Record<string, any> = {};
      for (const spec of availableTools) {
        tools[spec.name] = {
          description: spec.description,
          parameters: jsonSchema(spec.parameters),
        };
      }

      // 3. Query the configured language model
      const response = await generateText({
        model: this.model,
        system: this.systemInstruction,
        messages,
        tools,
      });

      // 4. Map output to structured AgenticDecision format (primaryCall uses .input in latest versions)
      if (response.toolCalls && response.toolCalls.length > 0) {
        const primaryCall = response.toolCalls[0];
        return {
          type: "tool_call",
          toolCall: {
            id: primaryCall.toolCallId,
            name: primaryCall.toolName,
            args: (primaryCall.input as Record<string, any>) || {},
          },
        };
      }

      if (response.text && response.text.trim().length > 0) {
        return {
          type: "complete",
          message: response.text,
        };
      }

      return {
        type: "fail",
        message:
          "No content or tool execution instructions generated by the model.",
      };
    } catch (error: any) {
      return {
        type: "fail",
        message: error?.message || "An unknown orchestration error occurred.",
      };
    }
  }
}
